### ISSUE TITLE
GRUB2 commandline on a sbRIO9628

### ISSUE THREAD

**Issue by hizlbuzz** [ni/grub#1]
Hi, 
Any way to get into the GRUB2 commandline on a sbRIO9628?

I tried to change the config in `/boot/efi/nilrt/grub.cfg`, changed the timeout to `set timeout=10`.
But on the serial line, I still can see the “Welcome to GRUB” label, for only like half a second.. 
Looks like the config is wrong or just ignored.

The reason for the question; I need to run a memtest, before booting..

**Comment by harisokanovic** [comment]
Try settings "bootdelay=10" in /boot/grub/grubenv instead.
E.g. run `grub-editenv /boot/grub/grubenv set bootdelay=10` from the shell.

**Comment by hizlbuzz** [comment]
Thank you Haris, works and already helped me a lot!
