### ISSUE TITLE
GRUB2 menuentries on sbRIO9628

### ISSUE THREAD

**Issue by hizlbuzz** [ni/grub#2]
This one is loosely related to #1, I miss an other piece.

- Where are the GRUB2 menuentries for runmode and safemode stored?
- How to add custom ones, respectively how to modify the existing menuentries?

According to `/boot/efi/nilrt/grub.cfg`, I would expect that menuentries in `/bootimage.cfg.d/` just appear..

**Comment by harisokanovic** [comment]
Search for "menuentry" in grub.cfg on the ESP (first partition of boot disk). You should find some lines like this:

```
               menuentry "$runmode_menu" {                        
                        $runmode_action                
                }  
                    
                menuentry "$safemode_menu" {
                        $safemode_action
                }
```

**Comment by hizlbuzz** [comment]
There is the magic! Thank you!

```bash
mount /dev/mmcblk1p1 boot0/
vi boot0/efi/boot/grub.cfg
```

**Comment by harisokanovic** [comment]
You can also find the NI Linux RT ESP with LABEL=nigrub
```
mount LABEL=nigrub /somewhere
```
